version: '2'
services:
  onboarding:
        # image: mysql:8.0
        build:
          context: .
        container_name: onboarding-test
        command: --default-authentication-plugin=mysql_native_password
    #    working_dir: /application
        volumes:
          - .:/app
        restart: always
        # environment:
        #     - MYSQL_PASS=root
        # # #   - MYSQL_ROOT_PASSWORD=
        # #   - MYSQL_DATABASE=my_db
        # #   - MYSQL_USER=db_user
        # #   - MYSQL_PASSWORD=.mypwd
        ports:
          - "9000:80"